@Port=7071

###

POST http://localhost:{{Port}}/api/CheckEmailValidity
accept: application/json
Content-Type: application/json
{
    "email": "johndoe@example"
}

POST http://localhost:{{Port}}/api/CheckEmailValidity?email=johndoe@example.com
accept: application/json
Content-Type: application/json